### ISSUE TITLE
request for code converter to generate c++ version struct from rust version struct

### ISSUE THREAD

**Issue by boltomli** [swigger/directcpp#1]
thanks for the bridge code and the sample, if possible please do share the code converter to help onboard :)

**Comment by swigger** [comment]
Now the rust2h tool is uploaded to directcpp/tools folder to demostrate how to convert rust structures into C struct.

NOTE: rust2h.py is NOT a full functional converter, it is designed to only support to convert some format of rust structures into C++ struct while keeping bit by bit compatiable.

Use it at your OWN RISK and you can extend it as you need.

The #[repr(C)] attribute is required to make a rust struct being able to be compatiable with C struct.
